version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=sample
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 120

  web:
    build: .
    command: sh -c 'alembic upgrade head && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - DB_ASYNC_CONNECTION_STR=${DB_ASYNC_CONNECTION_STR}
    depends_on:
      - db

volumes:
  postgres-data:
